### PR TITLE
click-click submission

### PR DESCRIPTION
**Pull request by probablyshabina**

### CODE REVIEW

**Comment by Akalanka47000** [comment]
Went through the node task and the core logic looks good. I do have a few confusions though. This'll be the flow from what I understood from the code, is there a specific reason behind designing it as such ? 

- Server started by running the server.js script
- Recipients added by invoking an endpoint in the above server
- Someone manually starts the index script which will read all added recipients and send them the emails

The same could be achieved with only 2 endpoints, excluding the get endpoints used to fetch data. Another concern is one would probably be confused around which is the entry point to this application since there are 3 JS scripts in the root directory and no scripts defined in the package.json. This or even adding some usage steps to the readme file wouldve reduced this confusion. If you can quickly have a look on these we can go ahead and merge this to main.

**Review by Akalanka47000 — APPROVED** [review]

**Comment by probablyshabina** [comment]
Thank you for the feedback. I will add the steps in the readme file to run the program and also clear the root directory and keep a single js script that performs the task of the assignement. Regarding the endpoints, by mentioning 'only 2 endpoints' did you mean the 2 put endpoints which are, one to update the click event and one to the event of successful email delivery?

**Comment by Akalanka47000** [comment]
> Thank you for the feedback. I will add the steps in the readme file to run the program and also clear the root directory and keep a single js script that performs the task of the assignement. Regarding the endpoints, by mentioning 'only 2 endpoints' did you mean the 2 put endpoints which are, one to update the click event and one to the event of successful email delivery?

Thanks, What I meant by the 2 endpoints are one `post` endpoint which'll take in a list of recipients, send the email and add the record into the database and one `put` endpoint to update that record on click. You don't need to change your implementation into this, just mentioned it as it's a simpler and cleaner way of getting the job done.

**Review by Akalanka47000 — APPROVED** [review]

**Comment by probablyshabina** [comment]
Thank you for your feedback. I have made some changes to my submission in order to make it more clear. If possible please review them and leave your feadbacks.

**Pull request merged**
