### PR TITLE
Assessment submission by Nilvin Sathnindu Kottage

### PR DESCRIPTION
**Pull request by sathninduk**
This pull request contains submissions for:
  1. Click-click (Node)
  2. Failure-retries (Node)
  3. Jokes-sdk (Node)
  4. Component-library (React)
and their readme files.

Submission by Nilvin Sathnindu Kottage (it22602282@my.sliit.lk)

### CODE REVIEW

**Comment by Akalanka47000** [comment]
Went through all 4 completed tasks, apart from some minor UI mismatches in the component library and some improvement which can be done in file structuring, this is overall quite a good submission. Kindly remove the node modules and .env file in the email task and we can go ahead and merge this.

**Review by Akalanka47000 — APPROVED** [review]

**Comment by sathninduk** [comment]
> Went through all 4 completed tasks, apart from some minor UI mismatches in the component library and some improvement which can be done in file structuring, this is overall quite a good submission. Kindly remove the node modules and .env file in the email task and we can go ahead and merge this.

Thank you for taking the time to review. I have committed the .env file to the repository by mistake, but I have now added the .gitignore file and excluded .env file from the repository. Thank you for bringing this to my attention.

Also, I have reverted and removed my component-library submission from the pull request, as I understand that you will be considering my other three submissions.

**Comment by Akalanka47000** [comment]
Thanks, you'll have to delete the node modules by hand and commit it once before adding the gitignore, else the deletions will not be tracked. The PR still contains those files. Also I suggest that you do a [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase#:~:text=What%20is%20git%20rebase%3F,of%20a%20feature%20branching%20workflow.) and remove the .env from the git history. Your keys are still visible for anyone going through the commit history. If you haven't used it before, better to backup your branch before attempting it.

**Comment by sathninduk** [comment]
A new PR was made.

**Comment by Akalanka47000** [comment]
Great, shall we remove the .idea folders and DS_STORE files in there as well please?. My bad forgot to mention it earlier.

**Comment by sathninduk** [comment]
> Great, shall we remove the .idea folders and DS_STORE files in there as well please?. My bad forgot to mention it earlier.

Done

**Pull request closed without merging**
