### PR TITLE
Dev assignment

### PR DESCRIPTION
**Pull request by eshanie-hub**

### CODE REVIEW

**Comment by Akalanka47000** [comment]
Thanks for the submission. There are a few addressable points here and it would be great if you could have a look at them before going through with this merge. Let me list them down.  It's fine if you take an extra day or two. Also I'm ignoring the fact that this uses neither React nor Tailwind CSS.

- UI
  - There's a margin around the entire page which doesn't look so good.
  - The carousels are having quite a bit of horizontal whitespacing on the sides.
  - The page is not mobile responsive.
  - All hover effects are instantaneous, we could smooth them by adding [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions).
  - Font, font colors, and font sizing doesn't match in a few places, for example the 4 cards and the carousels.
  - The subscribe email input has a white outline on click and its email icon isn't centered.

- File structure
  - All images are under one directory, we could separate them based on their purpose, for example icons could go to an icons folder, event images could go to an events folder, etc.
  - Same applies for the style.css file, it could be broken down based upon the components for example the styles related to the header could be in a header.css file. It'll greatly increase readability.

**Review by Akalanka47000 — CHANGES_REQUESTED** [review]
Thanks for the submission. There are a few addressable things which can be looked at before we go through with this merge. Let me list them down. It's fine if you take a day or two more in fixing some of them if not all. Also I'm ignoring the fact that this uses neither React nor Tailwind.

- UI
  - There's a margin around the entire page which doesn't look so good.
  - There's quite a bit of horizontal whitespace around the 2 carousels.
  - The page isn't mobile responsive.
  - All hover effects are instantaneous. We could smooth them out by using [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions).
  - Fonts, font sizing and colors don't match, for example in the 4 cards, carousels and footer.
  - The subscribe input has a white outline on click and its icon isn't centered.

- File structure
  - The images could be moved into separate folders based on their purpose. For example the icons could go into an icons folder and the event images into an event folder, etc. 
  - The style.css file could be broken down into pieces based on the components on the page. For example the styles related to the header could be in an header.css file. This'll greatly improve readability.

**Comment by eshanie-hub** [comment]
Thanks for the feedback. I will look in to the changes and try my level best to send them by today. Sorry for the delay in response.

**Comment by Akalanka47000** [comment]
> Thanks for the feedback. I will look in to the changes and try my level best to send them by today. Sorry for the delay in response.

No worries

**Comment by eshanie-hub** [comment]
Sent an updated version that includes mobile and tab version with the the changes requested.

**Comment by Akalanka47000** [comment]
> Sent an updated version that includes mobile and tab version with the the changes requested.

Looks good, would you be able to please clear out the duplicated images and the now obsolete style.css file as well. Also it looks nicer if the `Images` directory was in lowercase like the `css` dir, keeping the same case convention throughout a project is a good practice

**Comment by eshanie-hub** [comment]
Thanks for the feedback. Sent the updated version.

**Review by Akalanka47000 — APPROVED** [review]
Looks good

**Pull request merged**
